---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: app
  namespace: wcac
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wcac
              image: accesspc/website-crawl-and-check:v1.0.0
              volumeMounts:
                - name: config
                  mountPath: /app/config
                  readOnly: true
                - name: state
                  mountPath: /app/state
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: wcac-config
            - name: state
              persistentVolumeClaim:
                claimName: nfs-pvc
