---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wcac-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/wcac
    server: 192.168.68.2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  volumeMode: Filesystem
