---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wcac-pvc
  namespace: wcac
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: slow
  volumeMode: Filesystem
