---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  config.yml: |
    ---
    cron:
      seconds: {{ .Values.cron.seconds }}

    email:
      msg:
        ok:
          h1: OK
          h1_color: green
          status: up
        warn:
          h1: WARNING !!!
          h1_color: red
          status: down
      recipients:
        {{ - toYaml .Values.config.email.recipients | nindent 8 }}
      sender: {{ .Values.config.email.sender }}
      server: {{ .Values.config.email.server.host }}

    {{ - with .Values.config.websites }}
    websites:
      {{ - toYaml . | nindent 6 }}
    {{ - end }}
