---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{.Release.Name | quote}}
  namespace: {{.Release.Namespace | quote}}
spec:
  schedule: {{.Values.cron.schedule | quote}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{.Release.Name | quote}}
              image: accesspc/website-crawl-and-check:v{{.Chart.Version}}
              volumeMounts:
                - name: config
                  mountPath: /app/config
                  readOnly: true
                - name: state
                  mountPath: /app/state
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: {{.Release.Name | quote}}
            - name: state
              persistenVolumeClaim:
                claimName: {{printf "%s-%s" .Release.Name "pvc" | quote}}
