---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Release.Name | quote }}
          image: accesspc/website-crawl-and-check:{{ .Chart.Version }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            httpGet:
              path: /
              port: {{ .Values.service.containerPort }}
              scheme: HTTP
            timeoutSeconds: 2
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: {{ .Values.service.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 10Mi
              memory: 100Mi
            limits:
              cpu: 1
              ephemeral-storage: 100Mi
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name | quote }}
