---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{printf "%s-%s" .Release.Name "pv" | quote}}
spec:
  accessModes:
    {{- toYaml .Values.persistentvolume.accessmodes | nindent 4}}
  capacity:
    storage: {{.Values.persistentvolume.storage | quote}}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{.Values.persistentvolume.nfs.path | quote}}
    server: {{.Values.persistentvolume.nfs.server | quote}}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{.Values.persistentvolume.storageClassName | quote}}
  volumeMode: Filesystem
